### ISSUE TITLE
renderer breaking when zooming "through" objects?

### ISSUE THREAD

**Issue by ItsGamerik** [EvanCMcPheron/ascii_renderer#3]
when moving the camera based on the delta towards the scene, the renderer seems to break and display seemingly "random" lines on the canvas.

here is the code that was used to make the "zooming" effect:

```rust
self.renderer.camera.position.z = -7.0 + (self.time_offset * 2.0);
```

is there an explanation on why this could be?

**Comment by EvanCMcPheron** [comment]
Issue is resolved as of v1.1.1

The problem was with the code used to check if a point was on a screen or not. Instead of actually checking if the point is on the screen with some trig, it first maps every point to the screen and then runs through every edge combo and only draws a line if one or both of the points is on screen. Typically that works well, however the method that maps points to the screen (Camera::map_point_uv) can't distinguish between points behind the camera and in front of the camera. Because of that, when a point is directly behind the camera it is assumed to be on the screen because map_point_uv returns a vector that is within the bounds of the char buffer:

![image](https://github.com/EvanCMcPheron/ascii_renderer/assets/107580262/bacc287b-b3c5-41b5-9df3-12ed15099879)

The solution was just to create a method that checked if the point was truly on screen and use that to check whether or not a line should be drawn, rather than just the char buffer bounds check.
